import generated from "./generated-media.json";

/**
 * The media model. File-based media (photos, videos, audio, scanned letters)
 * is discovered from /public/media by `npm run media:build`, which writes
 * generated-media.json. That file is machine-owned — never edit it by hand.
 *
 * Pure-text quotes for the Letters wall live in ./letters.ts instead, since a
 * quote has no underlying file to scan.
 */

export type MediaType = "photo" | "video" | "audio" | "letter" | "quote";

export type Chapter =
  | "engagement"
  | "friday"
  | "ceremony"
  | "cocktail"
  | "reception"
  | "afterparty"
  | "toasts"
  | "dances"
  | "letters"
  | "vault";

export type Visibility = "public" | "hidden" | "vault";

export type MediaItem = {
  id: string;
  type: MediaType;
  src: string; // path relative to /public
  thumbnail?: string;
  blurDataURL?: string; // generated by build script
  width?: number;
  height?: number;
  focusY?: string; // vertical crop focus for cover images, e.g. "50%" (default ~32%)
  title?: string;
  caption?: string;
  alt?: string; // descriptive alt text; falls back to caption, then a generic label
  speaker?: string; // for audio/quote/letter
  speakerRole?: string; // "Best Man", "Father of the Bride"
  speakerPhoto?: string;
  chapter: Chapter;
  date?: string;
  featured?: boolean;
  visibility: Visibility;
  pullQuote?: string; // the highlighted line from a speech
  transcript?: string; // full transcript
  sortOrder?: number;
};

const ALL: MediaItem[] = (generated as MediaItem[]).slice();

/** Stable ordering: explicit sortOrder first, then id. */
function ordered(items: MediaItem[]): MediaItem[] {
  return items.slice().sort((a, b) => {
    const sa = a.sortOrder ?? Number.MAX_SAFE_INTEGER;
    const sb = b.sortOrder ?? Number.MAX_SAFE_INTEGER;
    if (sa !== sb) return sa - sb;
    return a.id.localeCompare(b.id);
  });
}

type Scope = { includeVault?: boolean };

/** Everything visible in a given scope. `hidden` items are never returned. */
export function allMedia({ includeVault = false }: Scope = {}): MediaItem[] {
  return ordered(
    ALL.filter((m) => {
      if (m.visibility === "hidden") return false;
      if (m.visibility === "vault") return includeVault;
      return true;
    }),
  );
}

export function byChapter(chapter: Chapter, scope: Scope = {}): MediaItem[] {
  return allMedia(scope).filter((m) => m.chapter === chapter);
}

export function byType(type: MediaType, scope: Scope = {}): MediaItem[] {
  return allMedia(scope).filter((m) => m.type === type);
}

/** The engagement set — Chapter I, In Frames. */
export function engagementPhotos(): MediaItem[] {
  return byChapter("engagement").filter((m) => m.type === "photo");
}

/** The single strongest frame for the full-bleed featured image. */
export function featuredImage(): MediaItem | undefined {
  const all = byType("photo");
  return all.find((m) => m.featured) ?? all[0];
}

/** The weekend archive chapters (post-wedding day-of photography). */
export const ARCHIVE_CHAPTERS: { key: Chapter; label: string }[] = [
  { key: "friday", label: "Friday" },
  { key: "ceremony", label: "Ceremony" },
  { key: "cocktail", label: "Cocktail" },
  { key: "reception", label: "Reception" },
  { key: "afterparty", label: "After Party" },
];

export function archivePhotos(scope: Scope = {}): MediaItem[] {
  const keys = ARCHIVE_CHAPTERS.map((c) => c.key);
  return allMedia(scope).filter(
    (m) => m.type !== "audio" && keys.includes(m.chapter),
  );
}

/** Voices tracks: toasts (audio) and dances (video), in program order. */
export function voiceTracks(scope: Scope = {}): MediaItem[] {
  return allMedia(scope).filter(
    (m) =>
      (m.chapter === "toasts" || m.chapter === "dances") &&
      (m.type === "audio" || m.type === "video"),
  );
}

export function vaultMedia(): MediaItem[] {
  return ALL.filter((m) => m.visibility === "vault");
}

/** Total counts, used by the Forthcoming chapter to know what has arrived. */
export function mediaCounts(): Record<Chapter, number> {
  const counts = {} as Record<Chapter, number>;
  for (const m of ALL) counts[m.chapter] = (counts[m.chapter] ?? 0) + 1;
  return counts;
}
